development:
  adapter: postgresql
  encoding: unicode
  database: code_happy_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: code_happy_test
  pool: 5
  username:
  password:
